defaults:
  - local_system   : ${oc.env:CMB_ML_LOCAL_SYSTEM}
  - file_system    : common_fs
  - pipeline       : assembly_sim  # Does not match below; used just for the combination executor
  - scenario       : scenario
  - splits         : "1-1"
  - model/sim      : sim
  - model/analysis : basic_analysis
  - override hydra/job_logging: custom_log
  - _self_

dataset_name   : "512_1_N${noise}_B${beam}_low_noise"
working_dir    : "Simulation_Working/"
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      noise: c, w
      beam: c, p, v
  run:
    dir        : Logs/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    dir        : Logs/${now:%Y-%m-%d-%H-%M-%S}  # Should be the same as run.dir
    subdir     : ${hydra.job.num}               # Subsequent jobs will include duplicate logs for all previous jobs. This is a minor bug, not worth fixing.
  verbose      : true

# Placeholders for the map types
noise:  ???
beam:  ???

# Settings below this point are used for interpolation.
# These are not to be used directly in the python
# They are picked up from here and MAY be used elsewhere in the yamls.
# In the scenario yaml
nside          : 512
detectors      : [30, 44, 70, 100, 143, 217, 353, 545, 857]
map_fields     : "I"

# In the simulation yaml (only relevant to the simulation portion of the pipeline)
nside_sky      : 2048
preset_strings : ["d9", "s4", "f1", "a1", "cib1", "ksz1", "tsz1", "rg1"]
# preset_strings : ["d9", "s4", "f1", "a1", "co1", "cib1", "ksz1", "tsz1", "rg1"]

# In the splits yaml
n_test_cap: null
