defaults:
  - local_system: ${oc.env:CMB_ML_LOCAL_SYSTEM}
  - file_system : common_fs
  - scenario    : scenario
  - splits      : "3-140"
  - _self_

dataset_name: DemoNotebook

# This would normally be in a separate file, but for the sake of the tutorial, we'll keep it here.
pipeline:
  ps_setup:
    assets_out:
      cmb_ps:
        handler: TextPowerSpectrum
        path_template: "{root}/{dataset}/{stage}/cmb_dummy_ps.fits"
    dir_name: A_PS_Setup
  ps2map:
    assets_out:
      cmb_map:
        handler: HealpyMap
        path_template: "{root}/{dataset}/{stage}/{split}/{sim}/cmb_dummy_map.fits"
    assets_in:
      cmb_ps: {stage: ps_setup}
    dir_name: B_CMB_Map
    splits: &all_splits
      - train
      - valid
      - test
    make_stage_log: true
  get_map_min_max:
    assets_out:
      cmb_map_min_max:
        handler: Config
        path_template: "{root}/{dataset}/{stage}/cmb_min_max.yaml"
    assets_in:
      cmb_map: {stage: ps2map}
    dir_name: C_Map_Min_Max
    # splits: *all_splits
    splits: &some_splits
      - train
      - valid
    make_stage_log: false

nside: 256
model:
  ps: [ 1.51935454e-13,
       -1.33044280e-10,
        4.87473463e-08,
       -9.68198860e-06,
        1.12257186e-03, 
       -7.62816561e-02,
        3.00276536e+00, 
       -4.49411282e+01,
        1.04893659e+03]
  max_ell: 200
n_workers: 6
