# DELETE ME
# defaults:
#   - local_system              : ${oc.env:CMB_ML_LOCAL_SYSTEM}
#   - file_system               : common_fs
#   - pipeline                  : pipe_noise_model
#   - scenario                  : scenario
#   - splits                    : all
#   - override hydra/job_logging: custom_log
#   - _self_

# dataset_name   : ${scenario.map_fields}_${scenario.nside}
# working_dir    : "NoiseModel/"
# n_sims         : 10
# detectors      : [30, 44, 70]  #, 100, 143, 217, 353, 545, 857]
# # detectors      : [30, 44, 70, 100, 143, 217, 353, 545, 857]
# map_fields     : "I"
# nside          : 512

# lmax_ratio     : 2  # This is not a bandwidth limited scenario!

# # Number of degrees total to mask around the galactic plane
# #    10, the default, will mask 5 degrees above and below the plane
# mask_galactic_size: 10
# # Smoothing (degrees) of the simple galactic plane mask
# mask_galactic_smooth: 1

