defaults:
  - local_system   : ${oc.env:CMB_ML_LOCAL_SYSTEM}
  - file_system    : common_fs
  - pipeline       : assembly_sim
  - scenario       : scenario_t
  - splits         : "1-1"
  # simulation must listed be after scenario and splits to build the simulation seed
  - model/sim      : sim_t
  - model/analysis : basic_analysis
  - override hydra/job_logging: custom_log
  - _self_

dataset_name: "noise_check/${scenario.map_fields}_${scenario.nside}_${splits.name}"
# dataset_name: "cmbnoise_${scenario.nside}/${scenario.map_fields}_${scenario.nside}_${splits.name}_noise_${model.sim.noise.noise_type}_cmb_${model.sim.cmb.cmb_type}"
working_dir : "Simulation_Working/"
hydra:
  # mode: MULTIRUN
  # sweeper:
  #   params:
  #     model/sim/cmb: cmb_empty, wmap9_mnu
  #     model/sim/noise: noise_empty, noise_variance
  run:
    dir: Logs/${now:%Y-%m-%d-%H-%M-%S}
  verbose: false

# Settings below this point are used for interpolation.
# These are not to be used directly in the python
# They are picked up from here and MAY be used elsewhere in the yamls.
# In the scenario yaml
nside          : 32
# detectors      : [30, 44, 70, 100, 143, 217, 353, 545, 857]
detectors      : [100]
map_fields     : "I"

# In the simulation yaml (only relevant to the simulation portion of the pipeline)
nside_sky      : 64
# preset_strings : ["d9"]  #, "s4", "f1", "a1", "co1", "cib1", "ksz1", "tsz1", "rg1"]
preset_strings : null  # ["d9"]  #, "s4", "f1", "a1", "co1", "cib1", "ksz1", "tsz1", "rg1"]

# In the splits yaml
n_test_cap: null
