defaults:
  - local_system   : generic_lab
  - file_system    : common_fs
  - pipeline       : assembly_sim_cmb_only
  - scenario       : scenario
  - splits         : all_2000
  - model/sim      : sim_flex_fgs
  - model/analysis : basic_analysis
  - override hydra/job_logging: custom_log
  - _self_

dataset_name: "${map_fields}_${scenario.nside}_${splits.name}_CMB_only/sigma_${param_sigma_fac}"
working_dir : "Simulation_Working/"
hydra:
  run:
    dir        : Logs/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    dir        : Logs/${now:%Y-%m-%d-%H-%M-%S}  # Should be the same as run.dir
    subdir     : ${hydra.job.num}               # Subsequent jobs will include duplicate logs for all previous jobs. 
                                                #   This is a minor bug, not worth fixing.
  verbose      : false

nside          : 32
cmb_lmax_fac   : 2.5
map_fields     : "I"
param_sigma_fac: 2
