defaults:
  - local_system   : generic_lab
  - file_system    : common_fs
  - pipeline       : assembly_sim_planck_fgs
  - scenario       : scenario
  - splits         : valid_only
  - model/sim      : sim_fgo
  - model/analysis : basic_analysis
  - override hydra/job_logging: custom_log
  - _self_

dataset_name: "${map_fields}_${scenario.nside}_${splits.name}"
working_dir : "Simulation_Working/"
hydra:
  run:
    dir        : Logs/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    dir        : Logs/${now:%Y-%m-%d-%H-%M-%S}  # Should be the same as run.dir
    subdir     : ${hydra.job.num}               # Subsequent jobs will include duplicate logs for all previous jobs. 
                                                #   This is a minor bug, not worth fixing.
  verbose          : false

# Settings below this point are used for interpolation.
# These are not to be used directly in the python
# They are picked up from here and MAY be used elsewhere in the yamls.
# In the scenario yaml
nside          : 128
detectors      : [30, 44, 70, 100, 143, 217, 353, 545, 857]
map_fields     : "I"  # Polarization is not supported at this time.

# In the simulation yaml (only relevant to the simulation portion of the pipeline)
nside_sky      : 256
min_obs_beam   : 82.5  # Arcmin. When making Nside=128 maps, if we convolve with smaller beams we get artifacts.
